CREATE TABLE Groups (id SERIAL PRIMARY KEY, name TEXT);
CREATE TABLE Kanji (id SERIAL PRIMARY KEY, kanji VARCHAR, group_id INTEGER REFERENCES Groups);
CREATE TABLE Meaning (meaning TEXT, kanji_id INTEGER REFERENCES Kanji);
CREATE TABLE Kunyomi (kun TEXT, kanji_id INTEGER REFERENCES Kanji);
CREATE TABLE Onyomi (Ony TEXT, kanji_id INTEGER REFERENCES Kanji);
CREATE TABLE CombGroups (id SERIAL PRIMARY KEY, name TEXT);
CREATE TABLE COMBINATIONS (id SERIAL PRIMARY KEY, kanji VARCHAR, meaning TEXT, yomikata TEXT, group_id INTEGER REFERENCES CombGroups);
CREATE TABLE Users (id SERIAL PRIMARY KEY, username TEXT UNIQUE, password TEXT, admin BOOLEAN);
