CREATE TABLE Groups (id SERIAL PRIMARY KEY, name TEXT);
CREATE TABLE Kanji (id SERIAL PRIMARY KEY, kanji VARCHAR UNIQUE, group_id INTEGER REFERENCES Groups);
CREATE TABLE Meaning (meaning TEXT, kanji_id INTEGER REFERENCES Kanji);
CREATE TABLE Kunyomi (kun TEXT, kanji_id INTEGER REFERENCES Kanji);
CREATE TABLE Onyomi (Ony TEXT, kanji_id INTEGER REFERENCES Kanji);
CREATE TABLE CombGroups (id SERIAL PRIMARY KEY, name TEXT);
CREATE TABLE COMBINATIONS (id SERIAL PRIMARY KEY, kanji VARCHAR UNIQUE, meaning TEXT, yomikata TEXT, group_id INTEGER REFERENCES CombGroups);
CREATE TABLE Users (id SERIAL PRIMARY KEY, username TEXT UNIQUE, password TEXT, admin BOOLEAN);
CREATE TABLE Answers (id SERIAL PRIMARY KEY, user_id INTEGER, kanji_id INTEGER, answer BOOLEAN);
